MTV/urls.py
from django.urls import path
from MTV import views

app_name = 'MTV'
urlpatterns = [
  path('',views.index),
 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from vote import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MTV/', include('MTV.urls')),
    path('vote/', include('vote.urls')),
    path('',views.index), #127.0.0.1:8000요청하면 여기에 매칭되고 MTV속의 views.index로 연결
    #메인페이시 설정을 위와 같이 하는거임
]

vote/urls.py

from django.urls import path, include
from . import views

app_name = 'vote'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:question_id>/',views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/result/', views.result, name='result'),

]

MTV/models.py
from django.db import models

# Create your models here.
class Board(models.Model): #models안의 Model을 상속
  title = models.CharField(max_length=30)
  content = models.TextField(max_length=500)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self): 
    return self.title
  #원래는 반환값이 primary key인 아이디를 반환하는데 타이틀을 반환하게 오버라이딩함
  #함수구성 추가는 마이그래이션 안해도 된다.

class Question(models.Model):
  title = models.CharField(max_length=100)
  content = models.TextField()
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return self.title

class Answer(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  content = models.TextField()
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return self.content

vote/models.py
from secrets import choice
from tkinter import CASCADE
from django.db import models

# Create your models here.
# NotNull은 기본값으로 설정되어 있어서 명시하지 않아도 된다.
class Question(models.Model):
  question_text = models.CharField(max_length=200)
  date = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.question_text

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)

  def __str__(self):
    return self.choice_text

MTV/views.py
from django.shortcuts import render
#from django.http import HttpResponse

# Create your views here.
def index(request): #request에 사용자의 요청정보가 저장
  return render(request, 'MTV/index.html') #render쓸때 꼭 요청정보를 request로 받아와 알맞는 렌더링페이지를 연결)


vote/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from vote.models import Question, Choice
# Create your views here.

def index(request):
  question_list = Question.objects.all().order_by()
  context = {'question_list' : question_list}
  return render(request, 'vote/index.html', context)


def detail(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  return render(request, 'vote/detail.html', {'question' : question})


def vote(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  try:
    select_choice = question.choice_set.get(pk=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
    context = {'question':question, 'error_msg':"You didn't select a choice"}
    return render(request, 'vote/detail.html', context)
  else:
    select_choice.votes += 1
    select_choice.save()
    return HttpResponseRedirect(reverse('vote:result', args=(question.id,)))


def result(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  return render(request, 'vote/result.html', {'question' : question})

templates/MTV/index.html
<html>
  <head>
    <title>Templates Test</title>
  </head>
  <body>
    <h1>Overview URL Link!</h1>
      <h4>
      <li><a href="http://127.0.0.1:8000/overview/index.html">
        http://127.0.0.1:8000/overview/index.html</a></li>
      <li><a href="http://127.0.0.1:8000/overview/python.html">
        http://127.0.0.1:8000/overview/python.html</a></li>
      <li><a href="http://127.0.0.1:8000/overview/django.html">
        http://127.0.0.1:8000/overview/django.html</a></li>
      </h4>

    <h1>Document URL Link!</h1>
      <h4>
      <li><a href="http://127.0.0.1:8000/document/python/tutorial.html">
        http://127.0.0.1:8000/document/python/tutorial.html</a></li>
      <li><a href="http://127.0.0.1:8000/document/python/install.html">
        http://127.0.0.1:8000/document/python/install.html</a></li>
      <li><a href="http://127.0.0.1:8000/document/django/tutorial.html">
        http://127.0.0.1:8000/document/django/tutorial.html</a></li>
      <li><a href="http://127.0.0.1:8000/document/django/install.html">
        http://127.0.0.1:8000/document/django/install.html</a></li>
      </h4>
  </body>
</html>

templates/vote/detail.html
<html>
  <head>
    <title>Vote Project</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>
    {% if error_msg %} <p><strong>{{ error_msg }}</strong></p>{% endif %}
    <form action="{% url 'vote:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br><br>
      {% endfor %}
      <input type="submit" value="vote" />
  </body>
</html>

templates/vote/index.html
<html>
  <head>
    <title>Vote Project</title>
  </head>

  <body>
    {% if question_list %}
      <ul>
        {% for question in question_list %}
          <h3>
            <li>
              <a href="/vote/{{question.id}}">{{question.question_text}}</a>
            </li>
          </h3>
        {% endfor %}
      </ul>
    {% else %}
      <h3>No Question List</h3>
    {% endif %}
  </body>
</html>

templates/vote/result.html
<html>
  <head>
    <title>Vote Project</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>
    <ul>
      {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} >> {{ choice.votes }} votes</li><br>
      {% endfor %}
      <a href="{% url 'vote:detail' question.id %}">Vote Again ?</a>
    </ul>
  </body>
</html>